filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - D:\Inspection\AdminPortal\Tenants_logs\LABTOP\logs\*\*\*-logs-*.txt
    fields:
      applicationType: inspectionLog
    fields_under_root: true
    multiline:
      pattern: "^[[0-9]{4}-[0-9]{2}-[0-9]{2}"
      negate: true
      match: after
  - type: log
    enabled: true
    paths:
      - D:\Inspection\AdminPortal\AdminPortal_websiste\logs\*-logs-*.txt
    fields:
      applicationType: inspectionAdminLog
    fields_under_root: true
    multiline:
      pattern: "^[[0-9]{4}-[0-9]{2}-[0-9]{2}"
      negate: true
      match: after
#============================= Filebeat modules ===============================
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false
  reload.period: 10s
  setup.template.settings:
  index.number_of_shards: 1
#----------------------------- Logstash output --------------------------------
output.logstash:
  hosts: ["localhost:8888"]
#================================ Processors =====================================
processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
  - if:
      equals:
        applicationType: inspectionLog
    then:
      - dissect:
          tokenizer: 'D:\Inspection\AdminPortal\Tenants_logs\LABTOP\logs\%{authority}\%{tenant}\%{FullappService}'
          field: log.file.path
          target_prefix: insp
    else:
      - dissect:
          tokenizer: 'D:\Inspection\AdminPortal\AdminPortal_websiste\logs\%{FullappService}'
          field: log.file.path
          target_prefix: insp
#================================ Logging =====================================
logging.level: debug
logging.selectors: ["*"]
